

export const packages = [
  {
    id: 1,
    title: "Bangkok & Pattaya Discovery",
    slug: "bangkok-pattaya-discovery",
    destination: "Thailand",
    duration: "5 Days",
    rating: 4.5,
    price: "35,000",
    image: "https://placehold.co/600x400.png",
    hint: "thailand beach",
    isWishlisted: false,
    agentId: 1,
  },
  {
    id: 2,
    title: "Enchanting Bali Getaway",
    slug: "enchanting-bali-getaway",
    destination: "Indonesia",
    duration: "7 Days",
    rating: 4.8,
    price: "45,000",
    image: "https://placehold.co/600x400.png",
    hint: "bali temple",
    isWishlisted: true,
    agentId: 2,
  },
  {
    id: 3,
    title: "Highlights of Vietnam",
    slug: "highlights-of-vietnam",
    destination: "Vietnam",
    duration: "6 Days",
    rating: 4.6,
    price: "42,000",
    image: "https://placehold.co/600x400.png",
    hint: "vietnam landscape",
    isWishlisted: false,
    agentId: 3,
  },
  {
    id: 4,
    title: "Singapore City Spectacular",
    slug: "singapore-city-spectacular",
    destination: "Singapore",
    duration: "4 Days",
    rating: 4.7,
    price: "55,000",
    image: "https://placehold.co/600x400.png",
    hint: "singapore skyline",
    isWishlisted: false,
    agentId: 4,
  },
  {
    id: 5,
    title: "Malaysian Marvels",
    slug: "malaysian-marvels",
    destination: "Malaysia",
    duration: "6 Days",
    rating: 4.4,
    price: "48,000",
    image: "https://placehold.co/600x400.png",
    hint: "malaysia city",
    isWishlisted: false,
    agentId: 2,
  },
  {
    id: 6,
    title: "Colors of Sri Lanka",
    slug: "colors-of-sri-lanka",
    destination: "Sri Lanka",
    duration: "8 Days",
    rating: 4.9,
    price: "60,000",
    image: "https://placehold.co/600x400.png",
    hint: "sri lanka tea plantation",
    isWishlisted: false,
    agentId: 4,
  },
  {
    id: 7,
    title: "Philippine Island Hopping",
    slug: "philippine-island-hopping",
    destination: "Philippines",
    duration: "10 Days",
    rating: 4.8,
    price: "75,000",
    image: "https://placehold.co/600x400.png",
    hint: "philippines boat",
    isWishlisted: false,
    agentId: 3,
  },
  {
    id: 8,
    title: "Laos Heritage Trail",
    slug: "laos-heritage-trail",
    destination: "Laos",
    duration: "5 Days",
    rating: 4.5,
    price: "40,000",
    image: "https://placehold.co/600x400.png",
    hint: "laos temple",
    isWishlisted: false,
    agentId: 1,
  },
];

export const destinations = [
  { name: "All", image: "https://placehold.co/100x100.png", hint: "world map" },
  { name: "Thailand", image: "https://placehold.co/100x100.png", hint: "thailand beach" },
  { name: "Vietnam", image: "https://placehold.co/100x100.png", hint: "vietnam landscape" },
  { name: "Singapore", image: "https://placehold.co/100x100.png", hint: "singapore skyline" },
  { name: "Malaysia", image: "https://placehold.co/100x100.png", hint: "malaysia city" },
  { name: "Indonesia", image: "https://placehold.co/100x100.png", hint: "bali temple" },
  { name: "Philippines", image: "https://placehold.co/100x100.png", hint: "philippines boat" },
  { name: "Sri Lanka", image: "https://placehold.co/100x100.png", hint: "sri lanka tea plantation" },
  { name: "Laos", image: "https://placehold.co/100x100.png", hint: "laos temple" },
];

export const testimonials = [
  {
    id: 1,
    name: "Anika Sharma",
    avatar: "https://placehold.co/100x100.png",
    hint: "woman smiling",
    quote: "Booking through Roam Southeast was a breeze! We got an incredible deal for our Bali trip directly from the local operators. So much better than the usual markups.",
  },
  {
    id: 2,
    name: "Rohan Patel",
    avatar: "https://placehold.co/100x100.png",
    hint: "man travel",
    quote: "The transparency is what I loved. I knew exactly who I was booking with in Thailand. The package was well-planned and everything was seamless. Highly recommended!",
  },
  {
    id: 3,
    name: "Priya Singh",
    avatar: "https://placehold.co/100x100.png",
    hint: "woman beach",
    quote: "Found the perfect family package to Singapore. The ability to chat with the DMC before booking was a fantastic feature. Will use again for sure.",
  },
];

export const agents = [
    {
        id: 1,
        name: "Siam Adventures",
        logo: "https://placehold.co/100x100.png",
        hint: "company logo",
        rating: 4.8,
        reviews: 120,
        specialty: "Thailand & Laos",
        phone: "+66 2 123 4567",
        email: "contact@siamadventures.com",
        website: "siamadventures.com",
        description: "Siam Adventures is a premier tour operator in Thailand, offering unforgettable experiences from the bustling streets of Bangkok to the serene temples of Chiang Mai. We pride ourselves on authentic local guides and personalized service.",
    },
    {
        id: 2,
        name: "Bali Horizons",
        logo: "https://placehold.co/100x100.png",
        hint: "travel company",
        rating: 4.9,
        reviews: 250,
        specialty: "Indonesia & Malaysia",
        phone: "+62 361 987 654",
        email: "info@balihorizons.com",
        website: "balihorizons.com",
        description: "Explore the magic of the Indonesian archipelago with Bali Horizons. From stunning beaches to ancient temples, our expert team curates journeys that capture the heart and soul of Southeast Asia.",
    },
    {
        id: 3,
        name: "Indochina Trails",
        logo: "https://placehold.co/100x100.png",
        hint: "logo travel",
        rating: 4.7,
        reviews: 180,
        specialty: "Vietnam & Philippines",
        phone: "+84 24 555 8888",
        email: "support@indochinatrails.com",
        website: "indochinatrails.com",
        description: "Discover the rich history and vibrant cultures of Vietnam and the Philippines with Indochina Trails. Our tours are designed to be immersive, educational, and breathtakingly beautiful.",
    },
    {
        id: 4,
        name: "Lanka Pearl Tours",
        logo: "https://placehold.co/100x100.png",
        hint: "tour company",
        rating: 4.9,
        reviews: 95,
        specialty: "Sri Lanka & Singapore",
        phone: "+94 11 222 3333",
        email: "bookings@lankapearl.com",
        website: "lankapearl.com",
        description: "Experience the teardrop island of Sri Lanka like never before. Lanka Pearl Tours offers bespoke itineraries covering ancient cities, lush tea plantations, and stunning coastlines.",
    }
];
